controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check
    controller: App\Controller\ApiLoginController::index
    methods: [POST]